[build]
  base = "/"
  command = "make build"
  publish = "public"
  functions = "functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/netlify/aws-lambda-go-example"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/hello-lambda/:splat"
  status = 200

